# command line: main.py linear_evaluation --config /mnt/netdisk/zhangjh/Code/AimCLR_loss/config/ntu60/linear_eval/linear_eval_aimclr_xsub_joint.yaml
work_dir: /mnt/netdisk/zhangjh/Code/SkeleMixCLR-main/work_dir/st_gcn/ntu/joint/xview/Standard/linear_tmp
weights: /mnt/netdisk/zhangjh/Code/SkeleMixCLR-main/work_dir/st_gcn/ntu/joint/xview/Standard/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_q_motion.fc, encoder_q_bone.fc, encoder_k, encoder_k_motion, encoder_k_bone, queue, queue_motion, queue_bone, encoder_q.global_head, encoder_q.local_head, encoder_q.Ap, encoder_q.global_mlps, encoder_q.tem_local_mlps, encoder_q.spa_local_mlps]
#start_epoch: 95
# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /mnt/netdisk/zhangjh/data/NTU60_frame64/xview/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /mnt/netdisk/zhangjh/data/NTU60_frame64/xview/val_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn_ntu.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True
# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 100
stream: 'joint'

# log
save_interval: -1
eval_interval: 5


