work_dir: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU60/xsub/motion_part_contrastive_tem02/
#weights: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU60/xsub/motion_MutalDDM_with4parallel_ablmask/epoch150_model.pt
#start_epoch: 150
randenque: False
exp_descri: part_contrastive_skeletonclr
# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU60_frame50/xsub/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xsub/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.hiclr.HiCLR
model_args:
  base_encoder: net.st_gcn_swap.Model
  pretrain: True
  feature_dim: 128
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.2
  mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True
  dropout_graph: 0.1
  add_graph: 0.00
  rep_ratio: 0.0
  doublequeue: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
#warmup_epochs: 10
step: [300]

mask_args:
  mask_ratio: 0.1
  person_num: 2
  joint_num: 25
  channel_num: 3

# training
device: [1]
batch_size: 128
test_batch_size: 128
num_epoch: 300
stream: 'motion'

# nearest neighbor mining
topk: 100
mining_epoch: 150

# log
save_interval: 50
eval_interval: -1
