work_dir: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU60/xsub/joint_cpm
#weights: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU60/xsub/joint_drop01add005mutalddm_withcos01_2stage/epoch150_model.pt
#start_epoch: 150
exp_descri: cpm
# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU60_frame50/xsub/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xsub/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.cpm.CPM
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: True
  feature_dim: 128
  queue_size: 65536
  momentum: 0.999
  Temperature: 0.07
  mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True
  #rep_ratio: 0.95
  dropout_graph: 0.1
  add_graph: 0.05
# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.3
optimizer: SGD
step: [250]

# training
device: [0]
batch_size: 512
test_batch_size: 128
num_epoch: 400
start_epoch: 0
stream: 'joint'

mask_args:
  mask_ratio: 0.1
  person_num: 2
  joint_num: 25
  channel_num: 3

# nearest neighbor mining
topk: 100
mining_epoch: 300

# log
save_interval: 300
eval_interval: -1
