base_lr: 0.1
batch_size: 128
debug: false
device:
- 1
eval_interval: -1
exp_descri: MutalDDM_with4parallel_ablmask
ignore_weights: []
log_interval: 100
mask_args:
    channel_num: 3
    joint_num: 25
    mask_ratio: 0.1
    person_num: 2
mining_epoch: 150
model: net.hiclr.HiCLR
model_args:
    Temperature: 0.07
    add_graph: 0.0
    base_encoder: net.st_gcn.Model
    dropout: 0.5
    dropout_graph: 0.0
    edge_importance_weighting: true
    feature_dim: 128
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    hidden_channels: 16
    hidden_dim: 256
    in_channels: 3
    mlp: true
    momentum: 0.999
    num_class: 60
    pretrain: true
    queue_size: 32768
nesterov: false
num_epoch: 300
num_worker: 4
optimizer: SGD
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: true
start_epoch: 0
step:
- 250
stream: joint
test_batch_size: 128
test_feeder: feeder.feeder
test_feeder_args: {}
topk: 1
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
    data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU60_frame50/xsub/train_position.npy
    label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xsub/train_label.pkl
    mmap: true
    shear_amplitude: 0.5
    temperal_padding_ratio: 6
use_gpu: true
warmup_epochs: 0
weight_decay: 0.0001
weights: null
work_dir: work_dir/NTU60/xsub/joint/
