work_dir: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU120/xsub/Transformer/motion_MutalDDM_with4parallel_ablmask02/linear_tmp

# weights: /data/gty/released_model/ntu60_xsub_motion.pt
weights: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU120/xsub/Transformer/motion_MutalDDM_with4parallel_ablmask02/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]
# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU120_frame50/xsub/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D_120/xsub/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU120_frame50/xsub/val_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D_120/xsub/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.dsta.DSTANet
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  transformer: True
  num_class: 120
  num_point: 25
  num_frame: 50
  num_subset: 3
  num_person: 2
  glo_reg_s: True
  att_s: True
  glo_reg_t: False
  att_t: False
  dropout: 0
  attentiondrop: 0.0
  dropout2d: 0
  use_spatial_att: True
  use_temporal_att: False
  use_pet: True
  use_pes: True
  fix_conv1: True
  #in_channels, out_channels, inter_channels, stride
  config: [ [32, 32, 16, 1], [32, 32, 16, 1],
            [32, 64, 16, 2], [64, 64, 16, 1],
            [64, 128, 32, 2], [128, 128, 32, 1],
            [128, 128, 32, 1], [128, 256, 32, 1],
  ]

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3
optimizer: SGD
step: [30,80]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 100
stream: 'motion'

# log
save_interval: -1
eval_interval: 5
