work_dir: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU60/xview/Transformer/motion_MutalDDM_with4parallel_ablmask/semi01

# weights: /data/gty/released_model/ntu60_xsub_motion.pt
weights: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU60/xview/Transformer/motion_MutalDDM_with4parallel_ablmask/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]
# feeder
train_feeder: feeder.ntu_feeder.Feeder_semieval
train_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU60_frame50/xview/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xview/train_label.pkl
  data_view: motion
  norm: False
test_feeder: feeder.ntu_feeder.Feeder_finetune
test_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU60_frame50/xview/val_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xview/val_label.pkl
  data_view: motion
  norm: False

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.dsta.DSTANet
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  transformer: True
  num_class: 60
  num_point: 25
  num_frame: 50
  num_subset: 3
  num_person: 2
  glo_reg_s: True
  att_s: True
  glo_reg_t: False
  att_t: False
  dropout: 0
  attentiondrop: 0.0
  dropout2d: 0
  use_spatial_att: True
  use_temporal_att: False
  use_pet: True
  use_pes: True
  fix_conv1: True
  #in_channels, out_channels, inter_channels, stride
  config: [ [32, 32, 16, 1], [32, 32, 16, 1],
            [32, 64, 16, 2], [64, 64, 16, 1],
            [64, 128, 32, 2], [128, 128, 32, 1],
            [128, 128, 32, 1], [128, 256, 32, 1],
  ]

# optim
nesterov: True
weight_decay: 5e-4
base_lr: 0.1
optimizer: SGD
warm_up_epoch: 5
step: [15,25]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 50

# log
save_interval: -1
eval_interval: 5
