work_dir: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU60/xsub/joint_skeletonMix_temincrease/
#weights: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/NTU60/xsub/joint_drop01add005MutalDDM_with4parallel1/epoch150_model.pt
#start_epoch: 150
exp_descri: skeletonclr_swap
# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: /mnt/netdisk/zhangjh/data/NTU60_frame64/xsub/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xsub/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.aimclr_swap.AimCLR
model_args:
  base_encoder: net.st_gcn_swap.Model
  pretrain: True
  feature_dim: 128
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  # spa_l, spa_u, tem_l, tem_u, repeat, loss_weight
  swap_cfg:
    swap_params: [[2, 3, 7, 11, 3, 1.],
                  ]
    swap_mode: 'swap'
    spatial_mode: 'semantic'
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [300]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 300
stream: 'joint'

mask_args:
  mask_ratio: 0.1
  person_num: 2
  joint_num: 25
  channel_num: 3

# nearest neighbor mining
topk: 1
mining_epoch: 300

# log
save_interval: 50
eval_interval: -1
