# command line: main.py linear_evaluation --config /mnt/netdisk/zhangjh/Code/AimCLR_loss/config/ntu60/linear_eval/linear_eval_aimclr_xsub_joint.yaml
work_dir: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/PKU1/xsub/bone_MutalDDM_with4parallel_ablmask/linear_tmp
weights: /mnt/netdisk/zhangjh/Code/AimCLR_loss/work_dir/PKU1/xsub/bone_MutalDDM_with4parallel_ablmask/epoch600_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]
#start_epoch: 95
# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/PKUMMD1_frame50/xsub/train_position.npy
  label_path: /mnt/netdisk/linlilang/PKUMMD-Skeleton/PKUMMD1/xsub/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/PKUMMD1_frame50/xsub/val_position.npy
  label_path: /mnt/netdisk/linlilang/PKUMMD-Skeleton/PKUMMD1/xsub/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 52
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True
# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [1]
batch_size: 128
test_batch_size: 128
num_epoch: 100
stream: 'bone'

# log
save_interval: -1
eval_interval: 5


